
default: &default
  adapter: mysql2
  pool: 5
  username: root
  password: 1

development:
  <<: *default
  database: management_tea_development

test:
  <<: *default
  database: management_tea_test

production:
   url: <%= ENV['DATABASE_URL'] %>
